target 'iosApp' do
  use_frameworks!
  platform :ios, '15.0'
  pod 'shared', :path => '../shared'
  pod("FirebaseAuth")
  pod("FirebaseDatabase")
  pod("FirebaseRemoteConfig")
  pod 'lottie-ios'
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'AlertToast'
end