//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `GoogleService-Info.plist`.
    static let googleServiceInfoPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "GoogleService-Info", pathExtension: "plist")
    /// Resource file `lottie_spaghetti_loader.json`.
    static let lottie_spaghetti_loaderJson = Rswift.FileResource(bundle: R.hostingBundle, name: "lottie_spaghetti_loader", pathExtension: "json")

    /// `bundle.url(forResource: "GoogleService-Info", withExtension: "plist")`
    static func googleServiceInfoPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.googleServiceInfoPlist
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "lottie_spaghetti_loader", withExtension: "json")`
    static func lottie_spaghetti_loaderJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.lottie_spaghetti_loaderJson
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    struct uiApplicationSceneManifest {
      static let _key = "UIApplicationSceneManifest"
      static let uiApplicationSupportsMultipleScenes = false

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 9 localization keys.
    struct localizable {
      /// Value: 檢查數據失敗，請重新再試。（錯誤碼：120）
      static let test_onboarding_loading_failed_checksum = Rswift.StringResource(key: "test_onboarding_loading_failed_checksum", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 無法連接至伺服器，請重新再試。
      static let test_onboarding_loading_failed_app_token = Rswift.StringResource(key: "test_onboarding_loading_failed_app_token", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 載入九巴／龍運路線數據失敗，請重新再試。
      static let test_onboarding_loading_failed_kmb = Rswift.StringResource(key: "test_onboarding_loading_failed_kmb", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 載入專線小巴路線數據失敗，請重新再試。
      static let test_onboarding_loading_failed_gmb = Rswift.StringResource(key: "test_onboarding_loading_failed_gmb", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 載入數據失敗，請重新再試。（錯誤碼：110）
      static let test_onboarding_loading_failed_other = Rswift.StringResource(key: "test_onboarding_loading_failed_other", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 載入新大嶼山巴士路線數據失敗，請重新再試。
      static let test_onboarding_loading_failed_nlb = Rswift.StringResource(key: "test_onboarding_loading_failed_nlb", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 載入新巴／城巴路線數據失敗，請重新再試。
      static let test_onboarding_loading_failed_ctb = Rswift.StringResource(key: "test_onboarding_loading_failed_ctb", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 載入港鐵路線數據失敗，請重新再試。
      static let test_onboarding_loading_failed_mtr = Rswift.StringResource(key: "test_onboarding_loading_failed_mtr", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: 載入輕鐵路線數據失敗，請重新再試。
      static let test_onboarding_loading_failed_lrt = Rswift.StringResource(key: "test_onboarding_loading_failed_lrt", tableName: "Localizable", bundle: R.hostingBundle, locales: [], comment: nil)

      /// Value: 檢查數據失敗，請重新再試。（錯誤碼：120）
      static func test_onboarding_loading_failed_checksum(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("test_onboarding_loading_failed_checksum", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "test_onboarding_loading_failed_checksum"
        }

        return NSLocalizedString("test_onboarding_loading_failed_checksum", bundle: bundle, comment: "")
      }

      /// Value: 無法連接至伺服器，請重新再試。
      static func test_onboarding_loading_failed_app_token(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("test_onboarding_loading_failed_app_token", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "test_onboarding_loading_failed_app_token"
        }

        return NSLocalizedString("test_onboarding_loading_failed_app_token", bundle: bundle, comment: "")
      }

      /// Value: 載入九巴／龍運路線數據失敗，請重新再試。
      static func test_onboarding_loading_failed_kmb(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("test_onboarding_loading_failed_kmb", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "test_onboarding_loading_failed_kmb"
        }

        return NSLocalizedString("test_onboarding_loading_failed_kmb", bundle: bundle, comment: "")
      }

      /// Value: 載入專線小巴路線數據失敗，請重新再試。
      static func test_onboarding_loading_failed_gmb(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("test_onboarding_loading_failed_gmb", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "test_onboarding_loading_failed_gmb"
        }

        return NSLocalizedString("test_onboarding_loading_failed_gmb", bundle: bundle, comment: "")
      }

      /// Value: 載入數據失敗，請重新再試。（錯誤碼：110）
      static func test_onboarding_loading_failed_other(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("test_onboarding_loading_failed_other", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "test_onboarding_loading_failed_other"
        }

        return NSLocalizedString("test_onboarding_loading_failed_other", bundle: bundle, comment: "")
      }

      /// Value: 載入新大嶼山巴士路線數據失敗，請重新再試。
      static func test_onboarding_loading_failed_nlb(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("test_onboarding_loading_failed_nlb", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "test_onboarding_loading_failed_nlb"
        }

        return NSLocalizedString("test_onboarding_loading_failed_nlb", bundle: bundle, comment: "")
      }

      /// Value: 載入新巴／城巴路線數據失敗，請重新再試。
      static func test_onboarding_loading_failed_ctb(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("test_onboarding_loading_failed_ctb", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "test_onboarding_loading_failed_ctb"
        }

        return NSLocalizedString("test_onboarding_loading_failed_ctb", bundle: bundle, comment: "")
      }

      /// Value: 載入港鐵路線數據失敗，請重新再試。
      static func test_onboarding_loading_failed_mtr(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("test_onboarding_loading_failed_mtr", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "test_onboarding_loading_failed_mtr"
        }

        return NSLocalizedString("test_onboarding_loading_failed_mtr", bundle: bundle, comment: "")
      }

      /// Value: 載入輕鐵路線數據失敗，請重新再試。
      static func test_onboarding_loading_failed_lrt(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("test_onboarding_loading_failed_lrt", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "test_onboarding_loading_failed_lrt"
        }

        return NSLocalizedString("test_onboarding_loading_failed_lrt", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R {
  fileprivate init() {}
}
