//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var infoPlist: infoPlist { .init(source: .init(bundle: bundle, tableName: "InfoPlist", preferredLanguages: preferredLanguages, locale: locale)) }
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func infoPlist(preferredLanguages: [String]) -> infoPlist {
      .init(source: .init(bundle: bundle, tableName: "InfoPlist", preferredLanguages: preferredLanguages, locale: locale))
    }
    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.infoPlist` struct is generated, and contains static references to 2 localization keys.
    struct infoPlist {
      let source: RswiftResources.StringResource.Source

      /// en translation: TBIA
      ///
      /// Key: CFBundleDisplayName
      ///
      /// Locales: en, zh-Hant
      var cfBundleDisplayName: RswiftResources.StringResource { .init(key: "CFBundleDisplayName", tableName: "InfoPlist", source: source, developmentValue: "TBIA", comment: nil) }

      /// en translation: TBIA
      ///
      /// Key: CFBundleName
      ///
      /// Locales: en, zh-Hant
      var cfBundleName: RswiftResources.StringResource { .init(key: "CFBundleName", tableName: "InfoPlist", source: source, developmentValue: "TBIA", comment: nil) }
    }

    /// This `_R.string.localizable` struct is generated, and contains static references to 2 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: TBIA
      ///
      /// Key: CFBundleDisplayName
      ///
      /// Locales: zh-Hant, en
      var cfBundleDisplayName: RswiftResources.StringResource { .init(key: "CFBundleDisplayName", tableName: "Localizable", source: source, developmentValue: "TBIA", comment: nil) }

      /// en translation: TBIA
      ///
      /// Key: CFBundleName
      ///
      /// Locales: zh-Hant, en
      var cfBundleName: RswiftResources.StringResource { .init(key: "CFBundleName", tableName: "Localizable", source: source, developmentValue: "TBIA", comment: nil) }
    }
  }

  /// This `_R.image` struct is generated, and contains static references to 10 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `app_icon`.
    var app_icon: ImageResource { .init(name: "app_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_bookmark_add`.
    var ic_bookmark_add: ImageResource { .init(name: "ic_bookmark_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_bookmark_remove`.
    var ic_bookmark_remove: ImageResource { .init(name: "ic_bookmark_remove", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_bus_24`.
    var ic_bus_24: ImageResource { .init(name: "ic_bus_24", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_edit_24`.
    var ic_edit_24: ImageResource { .init(name: "ic_edit_24", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_empty_list`.
    var ic_empty_list: ImageResource { .init(name: "ic_empty_list", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_order_24`.
    var ic_order_24: ImageResource { .init(name: "ic_order_24", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_search_24`.
    var ic_search_24: ImageResource { .init(name: "ic_search_24", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_settings_24`.
    var ic_settings_24: ImageResource { .init(name: "ic_settings_24", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_streetview_24`.
    var ic_streetview_24: ImageResource { .init(name: "ic_streetview_24", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 2 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `lottie_spaghetti_loader.json`.
    var lottie_spaghetti_loaderJson: RswiftResources.FileResource { .init(name: "lottie_spaghetti_loader", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }
}